In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [13]:
a = np.array([1,2,3,4,5,6,7,12])
a

array([ 1,  2,  3,  4,  5,  6,  7, 12])

In [14]:
a[2]

np.int64(3)

In [15]:
a[4]

np.int64(5)

In [19]:
a[7] = 220
a

array([  1,   2,  10,   4,   5,   6,   7, 220])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [24]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [25]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [28]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
n[0,1] = 20

In [30]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
n[2,1] = 99
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7, 99,  9]])

In [32]:
n[0]

array([ 1, 20,  3])

In [33]:
n[1] = [9,9,9]

In [34]:
n

array([[ 1, 20,  3],
       [ 9,  9,  9],
       [ 7, 99,  9]])

In [35]:
n[:,1]

array([20,  9, 99])

In [37]:
n[:,2]

array([3, 9, 9])

In [38]:
n[:,2] = [2,4,6]

In [39]:
n

array([[ 1, 20,  2],
       [ 9,  9,  4],
       [ 7, 99,  6]])

In [44]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [45]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [46]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [47]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [48]:
a + 1

array([1, 2, 3, 4, 5])

In [49]:
a * 2

array([0, 2, 4, 6, 8])

In [50]:
a * 100

array([  0, 100, 200, 300, 400])

In [51]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [53]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [54]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [56]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [57]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [58]:
a >= 2

array([False, False,  True,  True,  True])

In [59]:
a > b

array([False, False,  True,  True,  True])

In [60]:
a [a > b]

array([2, 3, 4])

In [61]:
a

array([0, 1, 2, 3, 4])

In [63]:
a.min()

np.int64(0)

In [64]:
a.max()

np.int64(4)

In [65]:
a.sum()

np.int64(10)

In [66]:
a.mean()

np.float64(2.0)

In [67]:
a.std()

np.float64(1.4142135623730951)

In [68]:
n.sum()

np.int64(157)