In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

In [16]:
billing = np.array([25000,40000,35000,18000,62000])

In [17]:
billing

array([25000, 40000, 35000, 18000, 62000])

In [18]:
print(type(billing))

<class 'numpy.ndarray'>


In [30]:
billing = np.array([25000,40000,35000,18000,62000])

In [31]:
billing

array([25000, 40000, 35000, 18000, 62000])

In [39]:
billing[2]

np.int64(35000)

In [40]:
billing[4]

np.int64(62000)

In [41]:
billing[1]

np.int64(40000)

In [42]:
billing[-1]

np.int64(62000)

In [43]:
billing[-2]

np.int64(18000)

In [44]:
billing[-3]

np.int64(35000)

In [45]:
billing[-5]

np.int64(25000)

In [6]:
arrears = np.zeros(7)

In [7]:
arrears

array([0., 0., 0., 0., 0., 0., 0.])

In [8]:
active_accounts = np.ones(7)

In [9]:
active_accounts

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
meter_readings = np.zeros(5, dtype=int)

In [14]:
meter_readings

array([0, 0, 0, 0, 0])

In [28]:
print("Arrears", arrears)
print("Active Accounts", active_accounts)
print("Meter Readings", meter_readings)

Arrears [0. 0. 0. 0. 0. 0. 0.]
Active Accounts [1. 1. 1. 1. 1. 1. 1.]
Meter Readings [0 0 0 0 0]


In [30]:
np.full(6,100000)

array([100000, 100000, 100000, 100000, 100000, 100000])

In [52]:
montly_target = np.full(6,100000)

In [53]:
monthly_target

array([100000, 100000, 100000, 100000, 100000, 100000])

In [39]:
minimum_bill = np.full(5, 10000)

In [40]:
minimum_bill

array([10000, 10000, 10000, 10000, 10000])

In [54]:
collection_rate = np.full(4, 0.95)

In [55]:
collection_rate

array([0.95, 0.95, 0.95, 0.95])

In [56]:
print("Monthly Target", monthly_target)
print("Minimum Bill", minimum_bill)
print("Collection Rate", collection_rate)

Monthly Target [100000 100000 100000 100000 100000 100000]
Minimum Bill [10000 10000 10000 10000 10000]
Collection Rate [0.95 0.95 0.95 0.95]


In [57]:
print(collection_rate.dtype)

float64


In [17]:
account_numbers = np.arange(1,21)
account_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
even_numbers = np.arange(2,22,2)
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
number_fives = np.arange(2,25,5)
number_fives

array([ 2,  7, 12, 17, 22])

In [19]:
billing_periods = np.arange(1,13)
billing_periods

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
countdown = np.arange(10,0,-1)
countdown

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [20]:
print("Account Numbers", account_numbers)
print("Even Numbers", even_numbers)
print("Billing Periods", billing_periods)
print("Count Down", countdown)

Account Numbers [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even Numbers [ 2  4  6  8 10 12 14 16 18 20]
Billing Periods [ 1  2  3  4  5  6  7  8  9 10 11 12]
Count Down [10  9  8  7  6  5  4  3  2  1]


In [22]:
consumption = np.linspace(10,50,5)
consumption

array([10., 20., 30., 40., 50.])

In [26]:
water_consumption = np.linspace(0,100,5)
water_consumption

array([  0.,  25.,  50.,  75., 100.])

In [27]:
collection_targets = np.linspace(50,100,6)
collection_targets

array([ 50.,  60.,  70.,  80.,  90., 100.])

In [28]:
temperature = np.linspace(20,35,4)
temperature

array([20., 25., 30., 35.])

In [32]:
interest_rates = np.linspace(0.05,0.25,5)
interest_rates

array([0.05, 0.1 , 0.15, 0.2 , 0.25])

In [33]:
print("Water Consumption", water_consumption)
print("Collection Targets", collection_targets)
print("Temperature", temperature)
print("Interest Rates", interest_rates)

Water Consumption [  0.  25.  50.  75. 100.]
Collection Targets [ 50.  60.  70.  80.  90. 100.]
Temperature [20. 25. 30. 35.]
Interest Rates [0.05 0.1  0.15 0.2  0.25]
